#pragma once

#define CFG_ECHO_SERVER_PORT 50022
#define CFG_ECHO_SERVER_MAX_PENDING_CLIENT_CONNECTIONS_IN 5
#define CFG_ECHO_SERVER_TIMEOUT_SECONDS 60

#define CFG_ECHO_SERVER_MAX_CLIENT_MSG_LEN 512

#define CFG_ECHO_SERVER_INFO_CMD_STR_PREFIX '>'
#define CFG_ECHO_SERVER_INFO_CMD_STR_CONNECTIONS_COUNT "Connections count: "
#define CFG_ECHO_SERVER_INFO_CMD_STR_MSGS_COUNT "Echoed messages count: "
